/**:
  ros__parameters:
    flight_time_s: 300.0

    pad_heartbeat_s: 20.0 # 1 per 20 seconds
    primary_heartbeat_s: 20.0
    secondary_heartbeat_s: 120.0 

    boost_threshold_mps2: 68.6 # 7g


    warn_battery_threshold_v: 10.75
    danger_battery_threshold_v: 10.5

    gpio_chip: "gpiochip0"
    runcam_pin: 1

    restart_command: "sudo systemctl restart atlas-flight.service"